version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_NAME=${APP_NAME}
      - MONGO_URL=mongodb://mongo:27017
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - LOG_FILE=${LOG_FILE}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DEBUG=${DEBUG}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - TOKEN_ALGORITHM=${TOKEN_ALGORITHM}
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    restart: unless-stopped

volumes:
  mongodb_data: